In [7]:
import pandas as pd
import pyarrow.parquet as pq
trips = pq.read_table('/Users/andrewchang/Desktop/Projects/data/fhvhv_tripdata_2023-04.parquet')
trips = trips.to_pandas()

In [10]:
trips.head(20)

,hvfhs_license_num,dispatching_base_num,originating_base_num,request_datetime,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,...,sales_tax,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,access_a_ride_flag,wav_request_flag,wav_match_flag
0,HV0003,B03404,B03404,2023-04-01 00:01:28,2023-04-01 00:02:41,2023-04-01 00:03:03,2023-04-01 00:15:42,174,126,5.100,...,1.82,0.00,0.0,0.00,13.83,N,N,,N,N
1,HV0003,B03404,B03404,2023-04-01 00:39:40,2023-04-01 00:41:20,2023-04-01 00:43:42,2023-04-01 01:01:08,211,163,3.110,...,3.56,2.75,0.0,9.52,24.84,N,N,,N,N
2,HV0003,B03404,B03404,2023-03-31 23:56:31,2023-04-01 00:00:20,2023-04-01 00:01:01,2023-04-01 00:09:48,222,76,2.400,...,1.08,0.00,0.0,0.00,8.10,Y,N,,N,N
3,HV0003,B03404,B03404,2023-04-01 00:12:35,2023-04-01 00:16:04,2023-04-01 00:17:17,2023-04-01 00:19:12,76,124,0.430,...,0.70,0.00,0.0,0.00,5.40,N,N,,N,N
4,HV0003,B03404,B03404,2023-04-01 00:46:23,2023-04-01 00:47:30,2023-04-01 00:47:49,2023-04-01 01:05:23,263,247,4.180,...,1.48,2.75,0.0,0.00,15.65,N,N,,N,N
5,HV0003,B03404,B03404,2023-04-01 00:18:41,2023-04-01 00:21:11,2023-04-01 00:22:29,2023-04-01 00:46:55,142,244,8.110,...,3.35,2.75,0.0,6.39,29.09,N,N,,N,N
6,HV0005,B03406,None,2023-03-31 23:56:53,NaT,2023-04-01 00:06:22,2023-04-01 00:26:59,79,246,2.651,...,2.36,2.75,0.0,0.00,16.15,N,N,N,N,Y
7,HV0003,B03404,B03404,2023-04-01 00:42:50,2023-04-01 00:46:44,2023-04-01 00:48:45,2023-04-01 01:20:12,231,149,11.300,...,3.95,2.75,0.0,0.00,42.75,N,N,,N,N
8,HV0003,B03404,B03404,2023-04-01 00:34:53,2023-04-01 00:36:42,2023-04-01 00:38:42,2023-04-01 00:50:13,230,48,0.920,...,0.81,2.75,0.0,5.00,7.70,N,N,,N,N
9,HV0005,B03406,None,2023-04-01 00:06:34,NaT,2023-04-01 00:08:03,2023-04-01 00:14:13,97,25,1.049,...,0.71,0.00,0.0,0.00,9.72,N,N,N,N,N
10,HV0005,B03406,None,2023-04-01 00:40:22,NaT,2023-04-01 00:43:04,2023-04-01 00:55:27,188,257,2.434,...,1.01,0.00,0.0,3.00,10.16,N,N,N,N,N
11,HV0003,B03404,B03404,2023-04-01 00:21:31,2023-04-01 00:22:39,2023-04-01 00:23:42,2023-04-01 00:38:41,179,75,5.780,...,2.72,0.00,0.0,0.00,16.04,N,N,,N,N
12,HV0005,B03406,None,2023-04-01 00:02:18,NaT,2023-04-01 00:11:08,2023-04-01 00:17:16,7,179,1.107,...,0.62,0.00,0.0,2.00,5.47,N,N,N,N,N
13,HV0005,B03406,None,2023-04-01 00:41:46,NaT,2023-04-01 00:44:56,2023-04-01 01:12:14,236,224,4.901,...,1.33,2.75,0.0,0.00,21.79,N,N,N,N,N
14,HV0005,B03406,None,2023-04-01 00:09:44,NaT,2023-04-01 00:14:20,2023-04-01 00:43:06,177,89,5.185,...,1.85,0.00,0.0,4.71,22.99,N,N,N,N,N
15,HV0005,B03406,None,2023-04-01 00:47:20,NaT,2023-04-01 00:49:09,2023-04-01 01:00:37,85,91,1.681,...,0.71,0.00,0.0,0.00,8.65,N,N,N,N,N
16,HV0003,B03404,B03404,2023-04-01 00:22:37,2023-04-01 00:26:06,2023-04-01 00:28:07,2023-04-01 01:01:19,231,263,9.010,...,4.35,2.75,0.0,0.00,33.67,N,N,,N,N
17,HV0003,B03404,B03404,2023-04-01 00:11:42,2023-04-01 00:16:13,2023-04-01 00:16:54,2023-04-01 00:33:32,106,256,4.140,...,2.06,0.00,0.0,0.00,21.74,N,N,,N,N
18,HV0003,B03404,B03404,2023-04-01 00:33:35,2023-04-01 00:35:17,2023-04-01 00:36:10,2023-04-01 01:00:25,256,236,9.650,...,3.34,2.75,0.0,6.72,33.62,N,N,,N,N
19,HV0003,B03404,B03404,2023-04-01 00:10:54,2023-04-01 00:12:34,2023-04-01 00:14:09,2023-04-01 00:33:28,127,32,4.200,...,2.06,0.00,0.0,0.00,16.42,N,N,,N,N